(define (sq x) (* x x))
(sq 21)
(define (fact n) (if (= n 1) 1 (* n (fact (- n 1)))))
(fact 20)
(fact 30)
(/ 1 3)
(/ 6 4)
(exact->inexact (/ 1 3))
(+ 0.5 1)
(sqrt 16)
(sqrt 2)
(cond ((> 3 5) 'a) ((< 3 5) 'b) (else 'c))
(let ((a 1) (b 2)) (+ a b))
(let* ((a 1) (b (+ a 1))) (* a b))
(let loop ((i 0) (acc '())) (if (= i 3) acc (loop (+ i 1) (cons i acc))))
(define x 10)
(set! x (+ x 1))
x
(and 1 2 3)
(or #f 7)
(display "hi") (newline)
undefined-name
(car '())
