; Code from SICP chapter 1 (Abelson, Sussman, Sussman / MIT Press), CC BY-SA 4.0.
; See book/ATTRIBUTION.md. Newton's method, fixed points, Ackermann, counting change, primes.
(define (improve guess x) (average guess (/ x guess)))
(define (good-enough? guess x) (< (abs (- (square guess) x)) 0.001))
(define (sqrt-iter guess x)
  (if (good-enough? guess x) guess (sqrt-iter (improve guess x) x)))
(define (my-sqrt x) (sqrt-iter 1.0 x))
(my-sqrt 9)

(define tolerance 0.00001)
(define (fixed-point f first-guess)
  (define (close-enough? v1 v2) (< (abs (- v1 v2)) tolerance))
  (define (try guess)
    (let ((next (f guess)))
      (if (close-enough? guess next) next (try next))))
  (try first-guess))
(fixed-point (lambda (y) (average y (/ 2 y))) 1.0)

(define (deriv-num g)
  (define dx 0.00001)
  (lambda (x) (/ (- (g (+ x dx)) (g x)) dx)))
(define (newton-transform g) (lambda (x) (- x (/ (g x) ((deriv-num g) x)))))
(define (newtons-method g guess) (fixed-point (newton-transform g) guess))
(newtons-method (lambda (x) (- (square x) 2)) 1.0)

(define (A x y)
  (cond ((= y 0) 0)
        ((= x 0) (* 2 y))
        ((= y 1) 2)
        (else (A (- x 1) (A x (- y 1))))))
(A 1 10)
(A 2 4)

(define (count-change amount)
  (define (first-denomination k)
    (cond ((= k 1) 1) ((= k 2) 5) ((= k 3) 10) ((= k 4) 25) ((= k 5) 50)))
  (define (cc amount kinds)
    (cond ((= amount 0) 1)
          ((or (< amount 0) (= kinds 0)) 0)
          (else (+ (cc amount (- kinds 1))
                   (cc (- amount (first-denomination kinds)) kinds)))))
  (cc amount 5))
(count-change 100)

(define (smallest-divisor n) (find-divisor n 2))
(define (find-divisor n test)
  (cond ((> (square test) n) n)
        ((= 0 (remainder n test)) test)
        (else (find-divisor n (+ test 1)))))
(define (prime? n) (= n (smallest-divisor n)))
(filter prime? (enumerate-interval 2 30))
(define (factorial n) (if (= n 1) 1 (* n (factorial (- n 1)))))
(factorial 40)
(expt 2 100)
(exact->inexact 1/7)
