; Code from SICP chapter 2 (Abelson, Sussman, Sussman / MIT Press), CC BY-SA 4.0.
; See book/ATTRIBUTION.md. Symbolic differentiation, sets, nested mappings, eight queens.
(define (variable? x) (symbol? x))
(define (same-variable? v1 v2) (and (variable? v1) (variable? v2) (eq? v1 v2)))
(define (=number? exp num) (and (number? exp) (= exp num)))
(define (make-sum a1 a2)
  (cond ((=number? a1 0) a2) ((=number? a2 0) a1)
        ((and (number? a1) (number? a2)) (+ a1 a2))
        (else (list '+ a1 a2))))
(define (make-product m1 m2)
  (cond ((or (=number? m1 0) (=number? m2 0)) 0)
        ((=number? m1 1) m2) ((=number? m2 1) m1)
        ((and (number? m1) (number? m2)) (* m1 m2))
        (else (list '* m1 m2))))
(define (sum? x) (and (pair? x) (eq? (car x) '+)))
(define (addend s) (cadr s))
(define (augend s) (caddr s))
(define (product? x) (and (pair? x) (eq? (car x) '*)))
(define (multiplier p) (cadr p))
(define (multiplicand p) (caddr p))
(define (deriv exp var)
  (cond ((number? exp) 0)
        ((variable? exp) (if (same-variable? exp var) 1 0))
        ((sum? exp) (make-sum (deriv (addend exp) var) (deriv (augend exp) var)))
        ((product? exp)
         (make-sum (make-product (multiplier exp) (deriv (multiplicand exp) var))
                   (make-product (deriv (multiplier exp) var) (multiplicand exp))))
        (else (error "unknown expression type -- DERIV" exp))))
(deriv '(+ x 3) 'x)
(deriv '(* x y) 'x)
(deriv '(* (* x y) (+ x 3)) 'x)

(define (element-of-set? x set)
  (cond ((null? set) #f) ((equal? x (car set)) #t) (else (element-of-set? x (cdr set)))))
(define (adjoin-set x set) (if (element-of-set? x set) set (cons x set)))
(define (union-set s1 s2) (if (null? s1) s2 (adjoin-set (car s1) (union-set (cdr s1) s2))))
(element-of-set? 3 '(1 2 3))
(union-set '(1 2) '(2 3))

(define (smallest-divisor n) (find-divisor n 2))
(define (find-divisor n test)
  (cond ((> (square test) n) n) ((= 0 (remainder n test)) test)
        (else (find-divisor n (+ test 1)))))
(define (prime? n) (= n (smallest-divisor n)))
(define (prime-sum? pair) (prime? (+ (car pair) (cadr pair))))
(define (make-pair-sum pair) (list (car pair) (cadr pair) (+ (car pair) (cadr pair))))
(define (prime-sum-pairs n)
  (map make-pair-sum
       (filter prime-sum?
               (flatmap (lambda (i) (map (lambda (j) (list i j)) (enumerate-interval 1 (- i 1))))
                        (enumerate-interval 1 n)))))
(prime-sum-pairs 6)

(define (queens board-size)
  (define empty-board '())
  (define (safe? k positions)
    (let ((new-row (car positions)) (rest (cdr positions)))
      (define (ok? others d)
        (cond ((null? others) #t)
              ((or (= (car others) new-row)
                   (= (car others) (+ new-row d))
                   (= (car others) (- new-row d))) #f)
              (else (ok? (cdr others) (+ d 1)))))
      (ok? rest 1)))
  (define (adjoin-position new-row k rest-of-queens) (cons new-row rest-of-queens))
  (define (queen-cols k)
    (if (= k 0) (list empty-board)
        (filter (lambda (positions) (safe? k positions))
                (flatmap (lambda (rest-of-queens)
                           (map (lambda (new-row) (adjoin-position new-row k rest-of-queens))
                                (enumerate-interval 1 board-size)))
                         (queen-cols (- k 1))))))
  (queen-cols board-size))
(length (queens 6))
(car (queens 6))
(length (queens 8))
(accumulate + 0 (enumerate-interval 1 100))
(fold-left - 0 '(1 2 3))
(fold-right - 0 '(1 2 3))
