; Code from SICP chapter 3 (Abelson, Sussman, Sussman / MIT Press), CC BY-SA 4.0.
; See book/ATTRIBUTION.md. Local state, queues, tables, infinite streams.
(define (make-account balance)
  (define (withdraw amount)
    (if (>= balance amount)
        (begin (set! balance (- balance amount)) balance)
        "Insufficient funds"))
  (define (deposit amount) (set! balance (+ balance amount)) balance)
  (define (dispatch m)
    (cond ((eq? m 'withdraw) withdraw)
          ((eq? m 'deposit) deposit)
          (else (error "Unknown request -- MAKE-ACCOUNT" m))))
  dispatch)
(define acc (make-account 100))
((acc 'withdraw) 50)
((acc 'withdraw) 60)
((acc 'deposit) 40)
((acc 'withdraw) 60)

(define (front-ptr q) (car q))
(define (rear-ptr q) (cdr q))
(define (set-front-ptr! q item) (set-car! q item))
(define (set-rear-ptr! q item) (set-cdr! q item))
(define (empty-queue? q) (null? (front-ptr q)))
(define (make-queue) (cons '() '()))
(define (insert-queue! q item)
  (let ((new-pair (cons item '())))
    (cond ((empty-queue? q) (set-front-ptr! q new-pair) (set-rear-ptr! q new-pair) q)
          (else (set-cdr! (rear-ptr q) new-pair) (set-rear-ptr! q new-pair) q))))
(define (delete-queue! q) (set-front-ptr! q (cdr (front-ptr q))) q)
(define q1 (make-queue))
(front-ptr (insert-queue! q1 'a))
(front-ptr (insert-queue! q1 'b))
(front-ptr (delete-queue! q1))

(define (make-table) (list '*table*))
(define (lookup key table)
  (let ((record (assoc key (cdr table))))
    (if record (cdr record) #f)))
(define (insert! key value table)
  (let ((record (assoc key (cdr table))))
    (if record
        (set-cdr! record value)
        (set-cdr! table (cons (cons key value) (cdr table)))))
  'ok)
(define t (make-table))
(insert! 'a 1 t)
(insert! 'b 2 t)
(lookup 'b t)
(lookup 'z t)

(define (integers-starting-from n) (cons-stream n (integers-starting-from (+ n 1))))
(define (stream-filter pred s)
  (cond ((stream-null? s) the-empty-stream)
        ((pred (stream-car s)) (cons-stream (stream-car s) (stream-filter pred (stream-cdr s))))
        (else (stream-filter pred (stream-cdr s)))))
(define (divisible? x y) (= (remainder x y) 0))
(define (sieve s)
  (cons-stream (stream-car s)
               (sieve (stream-filter (lambda (x) (not (divisible? x (stream-car s))))
                                     (stream-cdr s)))))
(define primes (sieve (integers-starting-from 2)))
(stream-head primes 15)
(stream-ref primes 50)

(define (stream-map2 proc . argstreams)
  (if (stream-null? (car argstreams))
      the-empty-stream
      (cons-stream (apply proc (map stream-car argstreams))
                   (apply stream-map2 (cons proc (map stream-cdr argstreams))))))
(define (add-streams s1 s2) (stream-map2 + s1 s2))
(define fibs (cons-stream 0 (cons-stream 1 (add-streams (stream-cdr fibs) fibs))))
(stream-head fibs 12)
(define doubles (cons-stream 1 (add-streams doubles doubles)))
(stream-head doubles 10)
