(define (make-counter)
  (let ((n 0))
    (lambda () (set! n (+ n 1)) n)))
(define c (make-counter))
(c)
(c)
(define q (list 1 2))
(set-car! q 9)
q
(set-cdr! q q)
(car (cdr (cdr q)))
(define (ints n) (cons-stream n (ints (+ n 1))))
(define s (ints 1))
(stream-head s 5)
(stream-ref s 100)
(define calls 0)
(define d (delay (begin (set! calls (+ calls 1)) 'v)))
(force d)
(force d)
calls
