; Vector operations, and the vector-based list memory of SICP 5.3.1
; (Abelson, Sussman, Sussman / MIT Press), CC BY-SA 4.0. See book/ATTRIBUTION.md.
(define v (make-vector 3 0))
v
(vector-set! v 0 'a)
(vector-set! v 1 "s")
v
(vector-ref v 0)
(vector-ref v 2)
(vector-length v)
(vector 1 2 3)
(make-vector 2)
(vector->list (vector 1 2 3))
(list->vector '(1 2 3))
(vector? v)
(vector? '(1 2))
#(1 2 3)
(equal? (vector 1 2) (vector 1 2))
(eqv? (vector 1 2) (vector 1 2))
(equal? (vector 1 (vector 2 "x")) (vector 1 (vector 2 "x")))
(vector-grow (vector 1 2) 4)
(subvector (vector 1 2 3 4) 1 3)
(vector-map (lambda (x) (* x x)) (vector 1 2 3))
(vector-ref (vector 1 2 3) 10)
(vector-ref '(1 2) 0)
(vector-length '(1 2))

; 5.3.1: lists represented in vector memory. `rest` is bound before the pair is
; allocated so the layout does not depend on operand evaluation order (cf. ex 3.8).
(define memory-size 30)
(define the-cars (make-vector memory-size 0))
(define the-cdrs (make-vector memory-size 0))
(define free-ptr 0)
(define nil-ptr -1)
(define (alloc-pair a d)
  (let ((p free-ptr))
    (set! free-ptr (+ free-ptr 1))
    (vector-set! the-cars p a)
    (vector-set! the-cdrs p d)
    p))
(define (list->memory lst)
  (if (null? lst)
      nil-ptr
      (let ((rest (list->memory (cdr lst))))
        (alloc-pair (car lst) rest))))
(define (memory->list p)
  (if (= p nil-ptr)
      '()
      (cons (vector-ref the-cars p) (memory->list (vector-ref the-cdrs p)))))
(define l1 (list->memory '(1 2 3 4 5)))
(memory->list l1)
free-ptr
(subvector the-cars 0 5)
(subvector the-cdrs 0 5)
(vector-ref the-cars l1)
