;; Prelude: procedures the book uses as if predefined, written in Scheme so readers can inspect them.
;; Everything here is the project's own code (MIT license).

(define (square x) (* x x))
(define (cube x) (* x x x))
(define (average x y) (/ (+ x y) 2))
(define (inc x) (+ x 1))
(define (dec x) (- x 1))
(define (identity x) x)
(define (compose f g) (lambda (x) (f (g x))))

(define (map f first . rest)
  (define (map1 lst)
    (if (null? lst) '() (cons (f (car lst)) (map1 (cdr lst)))))
  (define (any-null? lsts)
    (cond ((null? lsts) #f) ((null? (car lsts)) #t) (else (any-null? (cdr lsts)))))
  (define (cars lsts) (if (null? lsts) '() (cons (car (car lsts)) (cars (cdr lsts)))))
  (define (cdrs lsts) (if (null? lsts) '() (cons (cdr (car lsts)) (cdrs (cdr lsts)))))
  (define (mapn lsts)
    (if (any-null? lsts) '() (cons (apply f (cars lsts)) (mapn (cdrs lsts)))))
  (if (null? rest) (map1 first) (mapn (cons first rest))))

(define (for-each f lst)
  (cond ((null? lst) #t)
        (else (f (car lst)) (for-each f (cdr lst)))))

(define (filter pred lst)
  (cond ((null? lst) '())
        ((pred (car lst)) (cons (car lst) (filter pred (cdr lst))))
        (else (filter pred (cdr lst)))))

(define (fold-right op init lst)
  (if (null? lst) init (op (car lst) (fold-right op init (cdr lst)))))
(define (fold-left op init lst)
  (if (null? lst) init (fold-left op (op init (car lst)) (cdr lst))))
(define (reduce op init lst)
  (cond ((null? lst) init)
        ((null? (cdr lst)) (car lst))
        (else (fold-left op (car lst) (cdr lst)))))
(define accumulate fold-right)

(define (last-pair lst) (if (null? (cdr lst)) lst (last-pair (cdr lst))))
(define (list-copy lst) (if (null? lst) '() (cons (car lst) (list-copy (cdr lst)))))
(define (list-tail lst k) (if (= k 0) lst (list-tail (cdr lst) (- k 1))))
;; All car/cdr compositions two to four deep, as MIT provides them. The metacircular
;; evaluator of chapter 4 reaches for cdadr and cddddr, so partial coverage is a trap.
(define (caar p) (car (car p)))
(define (cadr p) (car (cdr p)))
(define (cdar p) (cdr (car p)))
(define (cddr p) (cdr (cdr p)))
(define (caaar p) (car (car (car p))))
(define (caadr p) (car (car (cdr p))))
(define (cadar p) (car (cdr (car p))))
(define (caddr p) (car (cdr (cdr p))))
(define (cdaar p) (cdr (car (car p))))
(define (cdadr p) (cdr (car (cdr p))))
(define (cddar p) (cdr (cdr (car p))))
(define (cdddr p) (cdr (cdr (cdr p))))
(define (caaaar p) (car (car (car (car p)))))
(define (caaadr p) (car (car (car (cdr p)))))
(define (caadar p) (car (car (cdr (car p)))))
(define (caaddr p) (car (car (cdr (cdr p)))))
(define (cadaar p) (car (cdr (car (car p)))))
(define (cadadr p) (car (cdr (car (cdr p)))))
(define (caddar p) (car (cdr (cdr (car p)))))
(define (cadddr p) (car (cdr (cdr (cdr p)))))
(define (cdaaar p) (cdr (car (car (car p)))))
(define (cdaadr p) (cdr (car (car (cdr p)))))
(define (cdadar p) (cdr (car (cdr (car p)))))
(define (cdaddr p) (cdr (car (cdr (cdr p)))))
(define (cddaar p) (cdr (cdr (car (car p)))))
(define (cddadr p) (cdr (cdr (car (cdr p)))))
(define (cdddar p) (cdr (cdr (cdr (car p)))))
(define (cddddr p) (cdr (cdr (cdr (cdr p)))))

;; Chapter 2 nested mappings lean on these constantly (prime-sum-pairs, queens).
(define (enumerate-interval low high)
  (if (> low high) '() (cons low (enumerate-interval (+ low 1) high))))
(define (flatmap proc seq) (accumulate append '() (map proc seq)))

;; Higher-order vector operations live here rather than in Rust: a primitive cannot call back
;; into the evaluator to apply a Scheme procedure.
(define (vector-map f v)
  (let ((n (vector-length v)))
    (let ((result (make-vector n #f)))
      (define (loop i)
        (if (= i n)
            result
            (begin (vector-set! result i (f (vector-ref v i))) (loop (+ i 1)))))
      (loop 0))))
(define (vector-for-each f v)
  (let ((n (vector-length v)))
    (define (loop i)
      (if (= i n)
          'done
          (begin (f (vector-ref v i)) (loop (+ i 1)))))
    (loop 0)))

(define (stream-null? s) (null? s))
(define (stream-car s) (car s))
(define (stream-cdr s) (force (cdr s)))
(define (stream-pair? s) (and (pair? s) (promise? (cdr s))))
(define (stream-ref s n) (if (= n 0) (stream-car s) (stream-ref (stream-cdr s) (- n 1))))
(define (stream-head s n)
  (if (= n 0) '() (cons (stream-car s) (stream-head (stream-cdr s) (- n 1)))))
(define (stream-tail s n) (if (= n 0) s (stream-tail (stream-cdr s) (- n 1))))
(define (stream-for-each proc s)
  (if (stream-null? s) 'done (begin (proc (stream-car s)) (stream-for-each proc (stream-cdr s)))))
(define (stream->list s . n)
  (cond ((stream-null? s) '())
        ((and (pair? n) (= (car n) 0)) '())
        ((pair? n) (cons (stream-car s) (stream->list (stream-cdr s) (- (car n) 1))))
        (else (cons (stream-car s) (stream->list (stream-cdr s))))))
(define (list->stream lst)
  (if (null? lst) the-empty-stream (cons-stream (car lst) (list->stream (cdr lst)))))
